### ISSUE TITLE
Installation issues in virtualenv on Python 2.7

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/tilde#100]
```
$ pip install quantum_esperanto
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting quantum_esperanto
  Using cached https://files.pythonhosted.org/packages/ee/a2/84e83630e506ace5c694a70c4e3ffaa921d2af987a91be86047b4a9d51b8/quantum_esperanto-0.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9QYYC9/quantum-esperanto/setup.py", line 30, in <module>
        exts = cythonize([vasp_ext])
      File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 967, in cythonize
        aliases=aliases)
      File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 812, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 111, in nonempty
        raise ValueError(error_msg)
    ValueError: 'src/vasp.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9QYYC9/quantum-esperanto/
```

**Comment by blokhin** [comment]
Not supported
